#!/usr/bin/env bash
# Output commands and exit upon any command failure
set -x
set -e
VENV_NAME="venv_$(basename $0)" # Use script name to generate local venv
REPORT_FILENAME=report_flake8.txt
function main(){
    # Get script directory
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    # Save current venv for later
    old_venv=$VIRTUAL_ENV
    if [ ! -d "${VENV_NAME}" ] ; then
        # only create if not present (optimization)
        virtualenv "${VENV_NAME}"
    fi
    source ${VENV_NAME}/bin/activate
    pushd ${SCRIPT_DIR}
    popd
    python3 -m pip install flake8
    rm -f ${REPORT_FILENAME} # delete report if existing
    python3 -m flake8 --exit-zero --tee --output-file=${REPORT_FILENAME} --count --max-line-length=110 ${SCRIPT_DIR}/ 
    echo "Successfully ran tool. Turning off verbose output"
    set +x
    set +e
    # Restore previous venv if it was set
    if [ ! -z ${old_venv} ] ; then
        echo "Restoring previous venv activation..."
        source ${old_venv}/bin/activate
    fi
}

main "$@"
