---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    kubeless: nats-trigger-controller
  name: nats-trigger-controller
  namespace: kubeless
spec:
  selector:
    matchLabels:
      kubeless: nats-trigger-controller
  template:
    metadata:
      labels:
        kubeless: nats-trigger-controller
    spec:
      containers:
      - image: bitnami/nats-trigger-controller:v1.0.0-alpha.8
        imagePullPolicy: IfNotPresent
        name: nats-trigger-controller
      serviceAccountName: controller-acct
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nats-controller-deployer
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - kubeless.io
  resources:
  - functions
  - natstriggers
  verbs:
  - get
  - list
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nats-controller-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-controller-deployer
subjects:
- kind: ServiceAccount
  name: controller-acct
  namespace: kubeless
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natstriggers.kubeless.io
spec:
  group: kubeless.io
  names:
    kind: NATSTrigger
    plural: natstriggers
    singular: natstrigger
  scope: Namespaced
  version: v1beta1
