apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-event-generator-k8saudit
  labels:
    app: falco-event-generator-k8saudit
  namespace: falco-event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco-event-generator-k8saudit
  template:
    metadata:
      labels:
        app: falco-event-generator-k8saudit
    spec:
      serviceAccount: falco-event-generator
      containers:
      - name: falco-event-generator
        image: falcosecurity/falco-event-generator
        imagePullPolicy: Always
        args: ["k8s_audit"]
