#!/bin/sh
set -e

NAME=falco

if [ -x "/etc/init.d/$NAME" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
				invoke-rc.d $NAME stop || exit $?
		else
				/etc/init.d/$NAME stop || exit $?
		fi
fi

