#!/bin/bash
#
# This script builds a precompiled version of falco-probe for a bunch of kernels
# The precompiled binary is then obtained at runtime by sysdig-probe-loader
# Ideally, the community should expand this stuff with better support
#
set -euo pipefail

#
# For continuous integration log purposes, wget prints its own output to stderr
# so it can be convenient to redirect it to a file. This can be done directly
# at runtime.
#

for builder in $(ls builders/* | grep -v common); do
  ${builder} $1
done
