apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostnetwork-deployment
  labels:
    app.kubernetes.io/name: hostnetwork-deployment
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: Create-HostNetwork-Pod
    message: Creating-deployment-with-hostNetwork-true-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hostnetwork-busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hostnetwork-busybox
        app.kubernetes.io/part-of: falco-event-generator
    spec:
      hostNetwork: true
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo sleeping; sleep 3600; done"]
