apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vanilla-role
  labels:
    app.kubernetes.io/name: vanilla-role
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: K8s-Role.Clusterrole-Created
    message: Creating-role
rules:
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vanilla-role-binding
  labels:
    app.kubernetes.io/name: vanilla-role-binding
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: K8s-Role.Clusterrolebinding-Created
    message: Creating-rolebinding
roleRef:
  kind: Role
  name: vanilla-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vanilla-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vanilla-serviceaccount
  labels:
    app.kubernetes.io/name: vanilla-serviceaccount
    app.kubernetes.io/part-of: falco-event-generator
    falco.rules: K8s-Serviceaccount-Created
    message: Creating-serviceaccount
