#!/bin/bash

set -euo pipefail

ARCH="x86_64"
KERNELDIR=/kernel${KERNELDIR}

if ! [ -n "${KERNEL_VERSION+1}" ] || [ -z "${KERNEL_VERSION}" ]; then
  KERNEL_VERSION=$(cat ${KERNELDIR}/include/config/kernel.release)
fi

PROBE_SUFFIX="${FALCO_VERSION}-${ARCH}-${KERNEL_VERSION}-${HASH}"
echo "* Building falco-probe-${PROBE_SUFFIX}.ko"
make -C "/usr/src/falco-${FALCO_VERSION}"
cp /usr/src/falco-${FALCO_VERSION}/falco-probe.ko \
  ${OUTPUT}/falco-probe-${PROBE_SUFFIX}.ko


KERNEL_MAJOR=$(echo ${KERNEL_VERSION} | cut -d. -f1)
KERNEL_MINOR=$(echo ${KERNEL_VERSION} | cut -d. -f2)
if [ ${KERNEL_MAJOR} -ge 4 ] && [ ${KERNEL_MINOR} -ge 14 ]; then
  echo "* Building falco-probe-bpf-${PROBE_SUFFIX}.ko"
  make -C "/usr/src/falco-${FALCO_VERSION}/bpf"
  cp /usr/src/falco-${FALCO_VERSION}/bpf/probe.o \
    ${OUTPUT}/falco-probe-bpf-${PROBE_SUFFIX}.o
fi

if [ -n "${HASH_ORIG+1}" ] && [ ! -z "${HASH_ORIG}" ] && [ "${HASH}" != "${HASH_ORIG}" ]; then
  PROBE_SUFFIX="${FALCO_VERSION}-${ARCH}-${KERNEL_VERSION}-${HASH_ORIG}"
  cp /usr/src/falco-${FALCO_VERSION}/falco-probe.ko \
    ${OUTPUT}/falco-probe-${PROBE_SUFFIX}.ko

  if [ -e /usr/src/falco-${FALCO_VERSION}/bpf/probe.o ]; then
    cp /usr/src/falco-${FALCO_VERSION}/bpf/probe.o \
      ${OUTPUT}/falco-probe-bpf-${PROBE_SUFFIX}.o
  fi
fi
