#!/bin/bash

set -euo pipefail

ARCH="x86_64"

KERNELDIR=/kernel${KERNELDIR}
KERNEL_VERSION=$(cat ${KERNELDIR}/include/config/kernel.release)

if [ -v DEBIAN ]; then
  echo "* Reverting changes done to Makefile"
  echo "* See https://github.com/draios/sysdig/blob/dev/scripts/build-probe-binaries#L433"

  sed -i '0,/MAKEARGS.*$/s||MAKEARGS := -C '"$(echo ${KERNELDIR} | sed  's/amd64/common/g')"' O='"${KERNELDIR}"'|' ${KERNELDIR}/Makefile

  KERNEL_VERSION=$(echo ${KERNELDIR} | cut -d/ -f5 | sed 's/linux-headers-//g')
fi

PROBE_SUFFIX="${FALCO_VERSION}-${ARCH}-${KERNEL_VERSION}-${HASH}"
echo "* Building falco-probe-${PROBE_SUFFIX}.ko"
make -C "/usr/src/falco-${FALCO_VERSION}"
cp /usr/src/falco-${FALCO_VERSION}/falco-probe.ko \
  ${OUTPUT}/falco-probe-${PROBE_SUFFIX}.ko


KERNEL_MAJOR=$(echo ${KERNEL_VERSION} | cut -d. -f1)
KERNEL_MINOR=$(echo ${KERNEL_VERSION} | cut -d. -f2)
if [ ${KERNEL_MAJOR} -ge 4 ] && [ ${KERNEL_MINOR} -ge 14 ]; then
  echo "* Building falco-probe-bpf-${PROBE_SUFFIX}.ko"
  make -C "/usr/src/falco-${FALCO_VERSION}/bpf"
  cp /usr/src/falco-${FALCO_VERSION}/bpf/probe.o \
    ${OUTPUT}/falco-probe-bpf-${PROBE_SUFFIX}.o
fi
