apiVersion: v1
kind: Service
metadata:
  name: {{ template "falco.fullname" . }}
  labels:
    app: {{ template "falco.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "falco.name" . }}
