find_path(GRPCXX_INCLUDE NAMES grpc++/grpc++.h)
if(GRPCXX_INCLUDE)
	set(GRPC_INCLUDE ${GRPCXX_INCLUDE})
else()
	find_path(GRPCPP_INCLUDE NAMES grpcpp/grpcpp.h)
	set(GRPC_INCLUDE ${GRPCPP_INCLUDE})
	add_definitions(-DGRPC_INCLUDE_IS_GRPCPP=1)
endif()
find_library(GRPC_LIB NAMES grpc)
find_library(GRPCPP_LIB NAMES grpc++)
if(GRPC_INCLUDE AND GRPC_LIB AND GRPCPP_LIB)
	message(STATUS "Found grpc: include: ${GRPC_INCLUDE}, C lib: ${GRPC_LIB}, C++ lib: ${GRPCPP_LIB}")
else()
	message(FATAL_ERROR "Couldn't find system grpc")
endif()
find_program(GRPC_CPP_PLUGIN grpc_cpp_plugin)
if(NOT GRPC_CPP_PLUGIN)
	message(FATAL_ERROR "System grpc_cpp_plugin not found")
endif()
