{{- if or .Values.falcoctl.artifact.install.enabled .Values.falcoctl.artifact.follow.enabled }}
{{- if and .Values.extra.registryCustomCaCert.enabled .Values.extra.registryCustomCaCert.cacert }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "falco.fullname" . }}-custom-ca
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
data:
  registry-cacert.pem:  {{ .Values.extra.registryCustomCaCert.cacert | b64enc | quote }}
{{- end }}
{{- end }}
