name: Builder Image Bumper

on:
  push:
    branches: [master]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      builder_changed: ${{ steps.filter.outputs.builder }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          builder:
            - 'docker/builder/**'

  update-builder-images:
    runs-on: ubuntu-22.04
    needs: paths-filter
    if: needs.paths-filter.outputs.builder_changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push new builder image
        if: needs.paths-filter.outputs.builder_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: docker/builder
          platforms: linux/amd64,linux/arm64
          tags: latest
          push: true
