name: Dev Packages and Docker images
on:
  push:
    branches: [master]

# Checks if any concurrent jobs is running for master CI and eventually cancel it
concurrency:
  group: ci-master
  cancel-in-progress: true  

jobs:
  build-dev-packages:
    uses: falcosecurity/falco/.github/workflows/reusable_build_packages.yaml@master
    with:
      arch: x86_64
    secrets: inherit
  
  build-dev-packages-arm64:
    uses: falcosecurity/falco/.github/workflows/reusable_build_packages.yaml@master
    with:
      arch: aarch64
    secrets: inherit
    
  publish-dev-packages:
    needs: [build-dev-packages, build-dev-packages-arm64]
    uses: falcosecurity/falco/.github/workflows/reusable_publish_packages.yaml@master
    with:
      bucket: '-dev'
      version: ${{ needs.build-dev-packages.outputs.version }}
    secrets: inherit
  
  # Both build-dev-docker and its arm64 counterpart require build-dev-packages because they use its output
  build-dev-docker:
    needs: [build-dev-packages, publish-dev-packages]
    uses: falcosecurity/falco/.github/workflows/reusable_build_docker.yaml@master
    with:
      arch: x86_64
      bucket: '-dev'
      version: ${{ needs.build-dev-packages.outputs.version }}
    secrets: inherit
    
  build-dev-docker-arm64:
    needs: [build-dev-packages, publish-dev-packages]
    uses: falcosecurity/falco/.github/workflows/reusable_build_docker.yaml@master
    with:
      arch: aarch64
      bucket: '-dev'
      version: ${{ needs.build-dev-packages.outputs.version }}
    secrets: inherit
    
  publish-dev-docker:
    needs: [build-dev-docker, build-dev-docker-arm64]
    uses: falcosecurity/falco/.github/workflows/reusable_publish_docker.yaml@master
    secrets: inherit
