name: 'Yamllint Github Actions'
on: 
  pull_request:
    branches: 
      - master

jobs: 
  lintFalcoRules: 
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: 'checkout falco-rules'
        uses: ibiqlik/action-yamllint@v3
        with: 
          files: /falco.yaml
          yamllint_strict: true
          yamllint_comment: true
          extends: default
          rules: 
            new-line-at-end-of-file:
              level: warning
            trailing-spaces:
              level: warning 